AppBundle\Entity\News:
    type: entity
    table: news
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        caption:
            type: text
            nullable: true
            length: 65535
            fixed: false
        content:
            type: text
            nullable: true
            length: 65535
            fixed: false
        datetime:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
